useTabs: true
semi: true
tabWidth: 4
singleQuote: true
bracketSpacing: true
trailingComma: es5
printWidth: 100

jsxSingleQuote: false
arrowParens: always

plugins:
    - prettier-plugin-tailwindcss
    - '@trivago/prettier-plugin-sort-imports'

pluginSearchDirs: ['.']
